### ISSUE TITLE
Allow multiple messages for a single update

### ISSUE THREAD

**Issue by SvenWritesCode** [alwaysbegrowing/telegram-standup-bot#27]
Right now, I submit a piece of text and then submit a photo. The photo is all that sends. I would like for the update to accept all messages up to some reasonable max. 

Upon first message say:
Awesome, thanks for the update. I will send this out at 11, but before then, feel free to add more to the update by sending me another message, view and edit your update by pressing the buttons below. 

There will be a view button that takes the user to their update draft on the web interface. 

There will be an edit button that takes the user to the edit interface on the web. 

A Start Over? button can be pressed to remove the whole update after a confirmation. The bot will say 

A great idea to start over, some of the best ideas come from writing down thoughts multiple times. 

Upon sending another message, the bot respond with:

Great. Got your additions! View or edit your updated update below.

**Comment by Geczy** [comment]
This is a good idea, and also a /preview command that shows your full update as it will be sent

It seems easy to code since we store all their submissions instead of overwriting anything. So we could just pick everything from last-sent-date (which we don't key yet, but can also be added very easily)

**Comment by Geczy** [comment]
added
